---
### default observation parameters needed for ZShooter simulation

object: configuration
alias: OBS
name: ZShooter_default_configuration
description: default config for zshooter sim
status: development
version: 0.1

packages:
- MaunaKea
- Keck
- ZShooter_v2

yamls:
- MaunaKea.yaml
- Keck.yaml
- ZShooter.yaml

properties:
  instrument : ZShooter_v2
  modes : ["SPEC"]
  airmass : 1.0
  pupil_angle : 0
  dit : 10
  ndit : 1
  mjdobs : 61132.0
  object : "Test"
  alt: 90.0
  az: 0.0
#  object: "Feige34"
#  ra : 159.90307
#  dec : 43.10256
#  declination : 43.10256
#  hour_angle : 0

mode_yamls:
- object: instrument
  alias: OBS
  name : SPEC
  description : "spectroscopic mode"
  yamls :
    - ZShooter_SPEC.yaml
    - ZShooter_DET.yaml

---
### default simulation parameters needed for a MICADO simulation
object : simulation
alias : SIM
name : ZShooter_simulation_paramters
description : RC simulation paramters which need to change for a zshooter run

properties :
  random :
    seed : 9001

  spectral :
    wave_unit : "um"
    wave_min : 0.3
    wave_mid : 1.0
    wave_max : 2.5
    spectral_bin_width: 0.00001 # in um
    spectral_resolution: 40000

  computing :
    preload_field_of_views : True

#  reports:
#    preamble_file: "../docs/.rst"
